"""Run hooks."""

from .deadline import (
    GLOBAL_DEADLINE_HOOK,
    SOFT_DEADLINE_MESSAGE,
    SOFT_DEADLINE_SECONDS,
)

__all__ = [
    "GLOBAL_DEADLINE_HOOK",
    "SOFT_DEADLINE_MESSAGE",
    "SOFT_DEADLINE_SECONDS",
]
